services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql_bis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bis
      MYSQL_DATABASE: f_flow
      # MYSQL_USER: se-group03
      # MYSQL_PASSWORD: 1234
    ports:
      - "3388:3306"
    volumes:
      - ./db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: pma5_bis
    environment:
      PMA_HOST: mysql_bis
    ports:
      - 8099:80


volumes:
  db_data: